### ISSUE TITLE
Sample paper compilation error

### ISSUE THREAD

**Issue by cole-wustl** [lubaochuan/ccsc-editor#8]
Hi, I just tried to import the "sample.zip" project into Overleaf as per the README instructions, but I encountered an error ("Extra \endgroup") upon compilation (see screenshot).
<img width="1538" alt="overleaf-error-screenshot" src="https://user-images.githubusercontent.com/50752159/140821130-a4c39cbf-e2e6-40b3-9d0e-bbf08ec330f4.png">

I had originally downloaded the sample.tex file from the repo and compiled with my own LaTeX (texlive on Mac OS), encountered the same issue, and thought it might just be my local LaTeX that was to blame.  

Any help/instructions you could provide would be appreciated.  Thanks!

**Comment by jteresco** [comment]
I also had this problem, and emailed @lubaochuan about it earlier today.  I was able to work around for now by replacing the first line with

<pre>\documentclass{article}</pre>

but I am not confident that this will produce the correct formatting for an upcoming CCSC submission.

**Comment by cole-wustl** [comment]
OK, thanks for the quick response and the workaround!

**Comment by lubaochuan** [comment]
@jteresco and @cole-wustl Thank you for the feedback. When you create a new project on overleaf, it uses the latest "TeX Live 2021", which throws the error. If you choose "Menu" on the upper left corner of your overleaf project and set "TeX Live version" to "2020", the error should disappear. 

I use the "combine" document class because it is used by the "combine" package for compiling papers into a single latex file for the journal. This way, if an author uses another package that conflicts with "combine", he/she would know it. I will find a solution to the problem and let you know. If you have a suggestion please let me know. Thanks!

**Comment by jteresco** [comment]
That did it for me, thanks!  I submitted a PR #9 proposing a note about this workaround in the README.md file for the repository.

**Comment by cole-wustl** [comment]
Worked for me too, thanks!  I'll close this issue.
